name: CD with Gradle

on:
  pull_request:
    branches:
      - develop
    types:
      - closed

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: "adopt"

      - name: Make application.yml
        run: |
          mkdir -p src/main/resources
          echo "${{ secrets.TEST_PROPERTIES }}" > src/main/resources/application.yml

      - name: Create Apple Private Key File
        run: |
          echo "${{ secrets.APPLE_PRIVATE_KEY }}" > src/main/resources/AuthKey.p8

      - name: First build for Generate API docs
        run: |
          chmod +x ./gradlew
          ./gradlew clean build

      - name: Second build for Include docs in jar
        run: ./gradlew build -x test

      - name: Docker build & push to Docker Hub
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -f Dockerfile -t ${{ secrets.DOCKER_TEST_REPO }} .
          docker push ${{ secrets.DOCKER_TEST_REPO }}

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.TEST_HOST }}
          username: ubuntu
          key: ${{ secrets.TEST_KEY }}
          script: |
            sudo docker rm -f $(sudo docker ps -qa)
            sudo docker pull ${{ secrets.DOCKER_TEST_REPO }}
            sudo docker-compose up -d
            sudo docker image prune -f
